### ISSUE TITLE
Add support for metadata in directives

### ISSUE THREAD

**Issue by jmgilman** [draug3n/sublime-beancount#4]
Source: https://docs.google.com/document/d/1wAMVrKIA2qtRGmoVDSUBJGmYZSygUaR0uOMW1GV3YE0/edit#heading=h.dplfcfjm39a1

Not sure if this is intended, but currently metadata has a bright red highlight around the text making it seem like an error. I've tried metadata in all different types of directives and it always gets the same highlight. 

Is this intended?

**Comment by jmgilman** [comment]
The newest commits ended up fixing this problem. 

I would recommend exporting another release with these changes as most people will be using the Package Manager plugin for Sublime to automatically download and install this. I believe the manager automatically downloads and installs the latest release (0.1.3 in my case) which does not include these rather important changes.

**Comment by Akuukis** [comment]
Good point, so let's wait for @draug3n to tag a new version.

**Comment by draug3n** [comment]
Will do. New to all this github-stuff :)

**Comment by draug3n** [comment]
Done! I hope.

**Comment by Akuukis** [comment]
It was updated to 0.2.0 in [Package manager](https://packagecontrol.io/packages/Beancount) 13 minutes ago. I can confirm that installing through package manager it works fine on Sublime 3 within Linux.

**Comment by jmgilman** [comment]
+1, thanks!
